In [214]:
import pandas as pd
df1 = pd.read_csv("googleplaystore.csv")
df2 = pd.read_csv("googleplaystore_user_reviews.csv")
import numpy as np

In [68]:
df1.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [69]:
df1.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [87]:
ch1 = df1.drop( columns= ['Reviews' , 'Type' , 'Price' , 'Content Rating' , 'Genres' , 'Last Updated' , 
                         'Current Ver', 'Android Ver'])
ch1 = ch1.dropna()
ch1.head()

,App,Category,Rating,Size,Installs
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,19M,"10,000+"
1,Coloring book moana,ART_AND_DESIGN,3.9,14M,"500,000+"
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,8.7M,"5,000,000+"
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,25M,"50,000,000+"
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,2.8M,"100,000+"

In [88]:
ch1[ (ch1['Installs'] == "Free") ]

,App,Category,Rating,Size,Installs
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,"1,000+",Free

In [89]:
ch1 = ch1.drop( [10472] )
ch1['Installs'] = pd.to_numeric( ch1['Installs'].apply( lambda x : x[:-1].replace(',','') ) )
ch1.head()

,App,Category,Rating,Size,Installs
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,19M,10000
1,Coloring book moana,ART_AND_DESIGN,3.9,14M,500000
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,8.7M,5000000
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,25M,50000000
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,2.8M,100000

In [90]:
df2.columns

Index(['App', 'Translated_Review', 'Sentiment', 'Sentiment_Polarity',
       'Sentiment_Subjectivity'],
      dtype='object')

In [140]:
ch2 = df2.drop(columns = ['Translated_Review' , 'Sentiment_Subjectivity' ])
ch2 = ch2.dropna()
ch2.head()

                     App Sentiment  Sentiment_Polarity
0  10 Best Foods for You  Positive                1.00
1  10 Best Foods for You  Positive                0.25
3  10 Best Foods for You  Positive                0.40
4  10 Best Foods for You  Positive                1.00
5  10 Best Foods for You  Positive                1.00

In [132]:
tr = ch1[ch1['Size'] != "Varies with device" ]

,App,Category,Rating,Size,Installs
9563,The dollar in mexico,FINANCE,4.5,3.2M,100000
7733,QRZ Assistant,COMMUNICATION,4.2,3.5M,100000
3438,Buzz Launcher-Smart&Free Theme,PERSONALIZATION,4.4,13M,10000000
4349,MapleStory M,FAMILY,3.5,82M,1000000
3313,Age Calculator,TOOLS,4.4,3.3M,1000000
9347,L.A. Crime Stories 2 Mad City Crime,GAME,4.2,42M,100000
2171,All-in-One Mahjong 3,FAMILY,4.4,16M,100
3624,Children's Stories 2018 - The Lion Come Lion,PARENTING,4.4,18M,10000
5630,Five nights at Minecraft,FAMILY,3.5,12M,1000000
5948,PBA® Bowling Challenge,SPORTS,4.3,87M,10000000

In [169]:
# ch2[ ch2['App'].isin(tr['App']) ]
ch2.groupby('App').count()[-40:]

,Sentiment,Sentiment_Polarity
App,,
"Hide App, Private Dating, Safe Chat - PrivacyHider",53,53
"Hide Something - Photo, Video",30,30
Hideman VPN,31,31
High Blood Pressure Symptoms,37,37
High-Powered Flashlight,34,34
"High-Speed Camera (GIF,Burst)",27,27
Hill Climb Racing,44,44
Hill Climb Racing 2,64,64
"Hily: Dating, Chat, Match, Meet & Hook up",102,102
Hinge: Dating & Relationships,69,69
HipChat - Chat Built for Teams,66,66
Hipmunk Hotels & Flights,35,35
Hitwe - meet people and chat,9,9
"Hole19: Golf GPS App, Rangefinder & Scorecard",19,19
Home Decor Showpiece Art making: Medium Difficulty,25,25
Home Scouting® MLS Mobile,32,32
Home Security Camera WardenCam - reuse old phones,26,26
Home Street – Home Design Game,57,57
Home Workout - No Equipment,26,26
Home Workout for Men - Bodybuilding,26,26
"Home workouts - fat burning, abs, legs, arms,chest",8,8
HomeWork,1,1
"Homes.com 🏠 For Sale, Rent",21,21
Homescapes,52,52
Homesnap Real Estate & Rentals,35,35
Homestyler Interior Design & Decorating Ideas,34,34
Homework Planner,37,37
Honkai Impact 3rd,76,76
Hopper - Watch & Book Flights,76,76
Horoscopes – Daily Zodiac Horoscope and Astrology,35,35
Horses Live Wallpaper,33,33
Hostelworld: Hostels & Cheap Hotels Travel App,65,65
Hot Wheels: Race Off,20,20
HotelTonight: Book amazing deals at great hotels,127,127
Hotels Combined - Cheap deals,36,36
Hotels.com: Book Hotel Rooms & Find Vacation Deals,68,68
Hotspot Shield Free VPN Proxy & Wi-Fi Security,34,34
Hotstar,32,32
Hotwire Hotel & Car Rental App,33,33
Housing-Real Estate & Property,21,21

In [184]:
apps = ["8 Ball Pool" , "AMC Theatres", "Hotstar" , "3D Live Neon Weed Launcher" ,  "A Word A Day" , "Zoom" , "Google" ]

In [185]:
t = ch2[ ch2['App'].isin(apps) ]
t.groupby('App').count()

                            Sentiment  Sentiment_Polarity
App
3D Live Neon Weed Launcher          2                   2
8 Ball Pool                       219                 219
A Word A Day                        4                   4
AMC Theatres                        6                   6
Google                             38                  38
Hotstar                            32                  32

         App       Category  Rating                Size   Installs
866  Hotstar  ENTERTAINMENT     4.3  Varies with device  100000000

In [189]:
x = ch1[ ch1['App'].isin(apps) ]

In [203]:
lc = pd.read_csv("chipotle_stores.csv")
loc = lc.sample(20)
loc = loc.drop(columns=['address' , 'latitude' , 'longitude' ])
loc

In [211]:
loc['id'] = range(len(loc))
loc

              state         location  id
523      California         Whittier   0
2223          Texas           Conroe   1
1723       New York        Tonawanda   2
1937           Ohio    North Olmsted   3
2138   Rhode Island       Middletown   4
2591  Washington DC    Washington DC   5
319      California             Napa   6
2011         Oregon           Eugene   7
426      California    San Francisco   8
1634       New York         Lawrence   9
2500       Virginia     Purcellville  10
1497  New Hampshire        Newington  11
187      California      Diamond Bar  12
144      California         Capitola  13
1995       Oklahoma            Moore  14
1063        Indiana   West Lafayette  15
1402      Minnesota  Vadnais Heights  16
1994       Oklahoma           Edmond  17
64          Arizona          Phoenix  18
2334          Texas       Lewisville  19

In [231]:
t['userId']= np.random.randint(0,19, (len(t)))
t['id'] = np.arange(len(t))
t

<ipython-input-231-a4bfa523764c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t['userId']= np.random.randint(0,19, (len(t)))
<ipython-input-231-a4bfa523764c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t['id'] = np.arange(len(t))

                              App Sentiment  Sentiment_Polarity   id  userId
872    3D Live Neon Weed Launcher  Positive            1.000000    0       3
877    3D Live Neon Weed Launcher  Positive            0.136364    1       0
1262                  8 Ball Pool  Negative           -0.013333    2      14
1263                  8 Ball Pool  Negative           -0.140000    3       5
1264                  8 Ball Pool  Negative           -0.303571    4       2
...                           ...       ...                 ...  ...     ...
64151                     Hotstar  Negative           -0.039062  296       0
64152                     Hotstar  Positive            0.138889  297      17
64153                     Hotstar   Neutral            0.000000  298       8
64154                     Hotstar  Positive            0.136364  299       2
64155                     Hotstar  Negative           -0.455000  300       4

[301 rows x 5 columns]

In [204]:
x
x = x.drop_duplicates('App')
x['id'] = range(len(x))

In [241]:
t['appId'] = t['App'].apply(lambda vt : x[ x['App'] == vt ].iloc[0]['id']  )
t

<ipython-input-241-529496ea4cdd>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t['appId'] = t['App'].apply(lambda vt : x[ x['App'] == vt ].iloc[0]['id']  )

,App,Sentiment,Sentiment_Polarity,id,userId,appId
872,3D Live Neon Weed Launcher,Positive,1.000000,0,3,4
877,3D Live Neon Weed Launcher,Positive,0.136364,1,0,4
1262,8 Ball Pool,Negative,-0.013333,2,14,2
1263,8 Ball Pool,Negative,-0.140000,3,5,2
1264,8 Ball Pool,Negative,-0.303571,4,2,2
...,...,...,...,...,...,...
64151,Hotstar,Negative,-0.039062,296,0,0
64152,Hotstar,Positive,0.138889,297,17,0
64153,Hotstar,Neutral,0.000000,298,8,0
64154,Hotstar,Positive,0.136364,299,2,0
64155,Hotstar,Negative,-0.455000,300,4,0

In [242]:
t.to_csv("3.csv"  , index=False)
x.to_csv("2.csv"  , index=False )
loc.to_csv("1.csv" , index=False)